# Generated by Django 6.0 on 2025-12-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('invoice', 'Invoice'), ('bill', 'Bill'), ('direct_expense', 'Direct Expense')], db_index=True, max_length=50)),
                ('transaction_number', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('partially_paid', 'Partially Paid')], db_index=True, max_length=20)),
                ('year', models.IntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-year', 'transaction_type'],
                'indexes': [models.Index(fields=['year', 'transaction_type'], name='transaction_year_e80d7f_idx'), models.Index(fields=['year', 'status'], name='transaction_year_334dba_idx'), models.Index(fields=['transaction_type', 'status'], name='transaction_transac_9f5934_idx')],
            },
        ),
    ]
